# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
from FRET_backend.mplwidget import MplWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1034, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.wellSlider = QtWidgets.QSlider(self.centralwidget)
        self.wellSlider.setGeometry(QtCore.QRect(10, 540, 541, 22))
        self.wellSlider.setMinimum(0)
        self.wellSlider.setMaximum(95)
        self.wellSlider.setOrientation(QtCore.Qt.Horizontal)
        self.wellSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.wellSlider.setTickInterval(1)
        self.wellSlider.setObjectName("wellSlider")
        #self.heatmapButton = QtWidgets.QPushButton(self.centralwidget)
        #self.heatmapButton.setGeometry(QtCore.QRect(911, 530, 111, 32))
        #self.heatmapButton.setObjectName("heatmapButton")
        self.rangeCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.rangeCheck.setGeometry(QtCore.QRect(20, 570, 71, 20))
        self.rangeCheck.setObjectName("rangeCheck")
        self.rangeText = QtWidgets.QLineEdit(self.centralwidget)
        self.rangeText.setGeometry(QtCore.QRect(160, 570, 81, 21))
        self.rangeText.setObjectName("rangeText")
        self.rangeLabel = QtWidgets.QLabel(self.centralwidget)
        self.rangeLabel.setGeometry(QtCore.QRect(110, 570, 51, 20))
        self.rangeLabel.setObjectName("rangeLabel")
        self.plotRangeButton = QtWidgets.QPushButton(self.centralwidget)
        self.plotRangeButton.setGeometry(QtCore.QRect(150, 590, 91, 32))
        self.plotRangeButton.setObjectName("plotRangeButton")
        self.leftComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.leftComboBox.setGeometry(QtCore.QRect(10, 0, 201, 32))
        self.leftComboBox.setObjectName("leftComboBox")
        self.leftComboBox.addItem("")
        self.leftComboBox.addItem("")
        self.leftComboBox.addItem("")
        self.leftComboBox.addItem("")
        self.leftComboBox.addItem("")
        self.leftComboBox.addItem("")
        self.leftComboBox.addItem("")
        self.leftComboBox.addItem("")
        self.rightComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.rightComboBox.setGeometry(QtCore.QRect(520, 0, 201, 32))
        self.rightComboBox.setObjectName("rightComboBox")
        self.rightComboBox.addItem("")
        self.rightComboBox.addItem("")
        self.rightComboBox.addItem("")
        self.rightComboBox.addItem("")
        self.rightComboBox.addItem("")
        self.rightComboBox.addItem("")
        self.rightComboBox.addItem("")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 1021, 468))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftGraphLayout = QtWidgets.QVBoxLayout()
        self.leftGraphLayout.setObjectName("leftGraphLayout")
        self.leftGraph = MplWidget(self.layoutWidget)
        self.leftGraph.setObjectName("leftGraph")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftGraph)
        self.verticalLayout.setObjectName("verticalLayout")
        self.leftGraphLayout.addWidget(self.leftGraph)
        self.horizontalLayout.addLayout(self.leftGraphLayout)
        self.rightGraphLayout = QtWidgets.QVBoxLayout()
        self.rightGraphLayout.setObjectName("rightGraphLayout")
        self.rightGraph = MplWidget(self.layoutWidget)
        self.rightGraph.setObjectName("rightGraph")
        self.rightGraphLayout.addWidget(self.rightGraph)
        self.horizontalLayout.addLayout(self.rightGraphLayout)
        self.leftExtractButton = QtWidgets.QPushButton(self.centralwidget)
        self.leftExtractButton.setGeometry(QtCore.QRect(390, 20, 112, 32))
        self.leftExtractButton.setObjectName("leftExtractButton")
        self.rightExtractButton = QtWidgets.QPushButton(self.centralwidget)
        self.rightExtractButton.setGeometry(QtCore.QRect(910, 20, 112, 32))
        self.rightExtractButton.setObjectName("rightExtractButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1034, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        #self.actionExtractRaw = QtWidgets.QAction(MainWindow)
        #self.actionExtractRaw.setObjectName("actionExtractRaw")
        self.menuFile.addAction(self.actionOpen)
        #self.menuTools.addAction(self.actionExtractRaw)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())



        # settings importer
        self.actionImportSettings = QtWidgets.QAction(MainWindow)
        self.actionImportSettings.setObjectName("actionImportSettings")
        self.menuTools.addAction(self.actionImportSettings)

        # get settings window back
        self.actionGetSettingsBack = QtWidgets.QAction(MainWindow)
        self.actionGetSettingsBack.setObjectName('actionGetSettingsBack')
        self.menuTools.addAction(self.actionGetSettingsBack)

        # switch to single view
        self.actionSwitchSingle = QtWidgets.QAction(MainWindow)
        self.actionSwitchSingle.setObjectName('actionSwitchSingle')
        self.menuTools.addAction(self.actionSwitchSingle)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        #self.heatmapButton.setText(_translate("MainWindow", "Plot contour"))
        self.rangeCheck.setText(_translate("MainWindow", "Range"))
        self.rangeLabel.setText(_translate("MainWindow", "Ranges"))
        self.plotRangeButton.setText(_translate("MainWindow", "Plot"))
        self.leftComboBox.setItemText(0, _translate("MainWindow", "E histogram"))
        self.leftComboBox.setItemText(1, _translate("MainWindow", "S vs. E"))
        self.leftComboBox.setItemText(2, _translate("MainWindow", "E vs. Tau(D(A))"))
        self.leftComboBox.setItemText(3, _translate("MainWindow", "Tau(D(A)/D(0)) vs. E"))
        self.leftComboBox.setItemText(4, _translate("MainWindow", "E vs. Tau(A)"))
        self.leftComboBox.setItemText(5, _translate("MainWindow", "FRET2CDE vs. E"))
        self.leftComboBox.setItemText(6, _translate("MainWindow", "rGG vs. E"))
        self.leftComboBox.setItemText(7, _translate("MainWindow", "rRR vs. E"))
        self.rightComboBox.setItemText(0, _translate("MainWindow", "E histogram"))
        self.rightComboBox.setItemText(1, _translate("MainWindow", "S histogram"))
        self.rightComboBox.setItemText(2, _translate("MainWindow", "N - molecules"))
        self.rightComboBox.setItemText(3, _translate("MainWindow", "Tau_(D(A)) histogram"))
        self.rightComboBox.setItemText(4, _translate("MainWindow", "Tau_(A) histogram"))
        self.rightComboBox.setItemText(5, _translate("MainWindow", "rGG histogram"))
        self.rightComboBox.setItemText(6, _translate("MainWindow", "rRR histogram"))
        self.leftExtractButton.setText(_translate("MainWindow", "Save Data"))
        self.rightExtractButton.setText(_translate("MainWindow", "Save Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionOpen.setText(_translate("MainWindow", "Open folder"))
        #self.actionExtractRaw.setText(_translate("MainWindow", "Extract Raw Data"))

        self.actionImportSettings.setText(_translate("MainWindow", "Import Settings File"))
        self.actionGetSettingsBack.setText(_translate("MainWindow", "Dock Settings Window"))
        self.actionSwitchSingle.setText(_translate("MainWindow", "Switch to single Well"))

    # function to create user warnings
    def user_warning(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # Message box for User Error Information
        self.msg = QtWidgets.QMessageBox(MainWindow)
        self.crit_icon = QtWidgets.QMessageBox.Critical
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
